import unittest
import pycfdi_transform.v2.sax.cfdi33.sax_handler as ct

class TestHanderCfdi33Nomina12Tests(unittest.TestCase):
    def test_transform_file_complete_nom(self):
        sax_handler = ct.SAXHandler().use_nomina12()
        cfdi_data = sax_handler.transform_from_file("./tests/Resources/nomina12/nom_complete.xml")
        self.assertIsNotNone(cfdi_data)
        self.assertTrue(cfdi_data['cfdi33']['version'] == '3.3')
        self.assertTrue(cfdi_data['cfdi33']['serie'] == 'G')
        self.assertTrue(cfdi_data['cfdi33']['folio'] == '370')
        self.assertTrue(cfdi_data['cfdi33']['fecha'] == '2020-02-25T23:17:37')
        self.assertTrue(cfdi_data['cfdi33']['no_certificado'] == '')
        self.assertTrue(cfdi_data['cfdi33']['subtotal'] == '1290.00')
        self.assertTrue(cfdi_data['cfdi33']['descuento'] == '')
        self.assertTrue(cfdi_data['cfdi33']['total'] == '1419.00')
        self.assertTrue(cfdi_data['cfdi33']['moneda'] == 'MXN')
        self.assertTrue(cfdi_data['cfdi33']['tipo_cambio'] == '')
        self.assertTrue(cfdi_data['cfdi33']['tipo_comprobante'] == 'I')
        self.assertTrue(cfdi_data['cfdi33']['metodo_pago'] == 'PPD')
        self.assertTrue(cfdi_data['cfdi33']['forma_pago'] == '99')
        self.assertTrue(cfdi_data['cfdi33']['condiciones_pago'] == '')
        self.assertTrue(cfdi_data['cfdi33']['lugar_expedicion'] == '56400')
        self.assertTrue(cfdi_data['cfdi33']['rfc_emisor'] == 'XIA190128J61')
        self.assertTrue(cfdi_data['cfdi33']['nombre_emisor'] == 'XIA190128J61')
        self.assertTrue(cfdi_data['cfdi33']['regimen_fiscal_emisor'] == '601')
        self.assertTrue(cfdi_data['cfdi33']['rfc_receptor'] == 'XIA190128J61')
        self.assertTrue(cfdi_data['cfdi33']['nombre_receptor'] == 'XIA190128J61')
        self.assertTrue(cfdi_data['cfdi33']['residencia_fiscal_receptor'] == '')
        self.assertTrue(cfdi_data['cfdi33']['num_reg_id_trib_receptor'] == '')
        self.assertTrue(cfdi_data['cfdi33']['uso_cfdi_receptor'] == 'G03')
        self.assertTrue(len(cfdi_data['cfdi33']['conceptos']) == 0)
        self.assertTrue(cfdi_data['cfdi33']['iva_traslado'] == '206.400000')
        self.assertTrue(cfdi_data['cfdi33']['ieps_traslado'] == '')
        self.assertTrue(cfdi_data['cfdi33']['isr_retenido'] == '')
        self.assertTrue(cfdi_data['cfdi33']['iva_retenido'] == '')
        self.assertTrue(cfdi_data['cfdi33']['ieps_retenido'] == '')
        self.assertTrue(cfdi_data['cfdi33']['total_impuestos_traslados'] == '206.40')
        self.assertTrue(cfdi_data['cfdi33']['total_impuestos_retenidos'] == '')
        self.assertTrue(cfdi_data['cfdi33']['complementos'] == 'ImpuestosLocales')
        self.assertTrue(cfdi_data['cfdi33']['addendas'] == '')
        self.assertTrue(len(cfdi_data['tfd']) == 0)
        self.assertTrue(len(cfdi_data['implocal']) == 0)